management:
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    # url: jdbc:postgresql://${DATABASE_URL}:5432/costmate
    # username: ${DATABASE_USER}
    # password: ${DATABASE_PASSWORD}
    username: usr_costmate
    url: jdbc:postgresql://svc-postgres.database.svc.cluster.local:5432/costmate
    password: xadkncbirheywv
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
  mvc:
    locale: en_US
logging:
  level:
    br:
      com:
        artvimluc:
          costmate: DEBUG
server:
  servlet:
    context-path: /costmate
  port: '8080'

