CREATE TABLE PLAN_MONTH(
    ID BIGSERIAL PRIMARY KEY,
    REFERENCE_MONTH SMALLINT NOT NULL,
    REFERENCE_YEAR SMALLINT NOT NULL,
    TOTAL_EXPENSES DECIMAL,
    TOTAL_INCOME DECIMAL,
    GOAL DECIMAL,
    SURPLUS DECIMAL
);

CREATE TABLE INCOME(
    ID BIGSERIAL PRIMARY KEY,
    PLAN_MONTH_ID BIGINT NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    INCOME_VALUE DECIMAL NOT NULL,
    FOREIGN KEY (PLAN_MONTH_ID) references PLAN_MONTH(ID)
);

CREATE TABLE EXPENSE(
    ID BIGSERIAL PRIMARY KEY,
    PLAN_MONTH_ID BIGINT NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    EXPENSE_VALUE DECIMAL NOT NULL,
    REFUND BOOLEAN NOT NULL,
    INSTALLMENT SMALLINT,
    TOTAL_INSTALLMENTS SMALLINT,
    RECEIPT_FILE VARCHAR(255),
    RECEIPT_FILE_UPLOADED BOOLEAN NOT NULL,
    FOREIGN KEY (PLAN_MONTH_ID) references PLAN_MONTH(ID)
);
